// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mandelbrot_esc
IntegerVector mandelbrot_esc(NumericVector x, NumericVector y, int maxit, double escape);
RcppExport SEXP _faroutman_mandelbrot_esc(SEXP xSEXP, SEXP ySEXP, SEXP maxitSEXP, SEXP escapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type escape(escapeSEXP);
    rcpp_result_gen = Rcpp::wrap(mandelbrot_esc(x, y, maxit, escape));
    return rcpp_result_gen;
END_RCPP
}
// fibonacci_esc
IntegerVector fibonacci_esc(NumericVector x, NumericVector y, int maxit, double escape);
RcppExport SEXP _faroutman_fibonacci_esc(SEXP xSEXP, SEXP ySEXP, SEXP maxitSEXP, SEXP escapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type escape(escapeSEXP);
    rcpp_result_gen = Rcpp::wrap(fibonacci_esc(x, y, maxit, escape));
    return rcpp_result_gen;
END_RCPP
}
// cosine_esc
IntegerVector cosine_esc(NumericVector x, NumericVector y, int maxit, double escape);
RcppExport SEXP _faroutman_cosine_esc(SEXP xSEXP, SEXP ySEXP, SEXP maxitSEXP, SEXP escapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type escape(escapeSEXP);
    rcpp_result_gen = Rcpp::wrap(cosine_esc(x, y, maxit, escape));
    return rcpp_result_gen;
END_RCPP
}
// exp_esc
IntegerVector exp_esc(NumericVector x, NumericVector y, int maxit, double escape);
RcppExport SEXP _faroutman_exp_esc(SEXP xSEXP, SEXP ySEXP, SEXP maxitSEXP, SEXP escapeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type escape(escapeSEXP);
    rcpp_result_gen = Rcpp::wrap(exp_esc(x, y, maxit, escape));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_faroutman_mandelbrot_esc", (DL_FUNC) &_faroutman_mandelbrot_esc, 4},
    {"_faroutman_fibonacci_esc", (DL_FUNC) &_faroutman_fibonacci_esc, 4},
    {"_faroutman_cosine_esc", (DL_FUNC) &_faroutman_cosine_esc, 4},
    {"_faroutman_exp_esc", (DL_FUNC) &_faroutman_exp_esc, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_faroutman(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
